---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.0
    hooks:
      - id: docker-compose-check
      - id: hadolint
